### ISSUE TITLE
Requests to the endpoint time out

### ISSUE THREAD

**Issue by cogwirrel** [timrogers/ba_rewards#1]
Hey Tim,

It appears that hitting that endpoint times out now, eg:

http://dev1-flightavail-avios.bitnamiapp.com:8080/flight-availability-ws/departure/cities/LON/destination/SFO

Is there an updated endpoint we need to use? Or has the Avios Flight Finder app tightened their security?

Thanks,
Jack

**Comment by cogwirrel** [comment]
Turns out it was a firewall issue!

**Comment by queeno** [comment]
I am having the same issue - I cannot establish a TCP connection to that endpoint, although I suspect the endpoint might have changed by now. Do you happen to know what the new one is?
